kind: secret
name: aws_secret_access_key
get:
  path: drone-cred-secrets
  name: aws_secret_access_key
---
kind: secret
name: aws_access_key_id
get:
  path: drone-cred-secrets
  name: aws_access_key_id
---
kind: secret
name: ssh_key
get:
  path: drone-ssh-rw-key
  name: drone-aws-rw-key
---
kind: secret
name: webex_room
get:
  path: webex-notification
  name: webex_room
---
kind: secret
name: notify_access_token
get:
  path: webex-notification
  name: notify_access_token
---
kind: secret
name: argocd-username
get:
  path: argocd-credentials
  name: username
---
kind: secret
name: argocd-password
get:
  path: argocd-credentials
  name: password
---
kind: secret
name: sonar_host
get:
  path: drone-cred-secrets
  name: sonar_host
---
kind: secret
name: sonar_token
get:
  path: drone-cred-secrets
  name: sonar_token
---
kind: pipeline
name: build
type: kubernetes

trigger:
  branch:
  - release/*
  - drone
  - develop
  event:
  - push
  - custom

clone:
  depth: 50

steps:
- name: static code analysis
  image: 310830963532.dkr.ecr.eu-central-1.amazonaws.com/drone-sonar-plugin:2022-08-14-180115
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
- name: "publish-dev"
  image: plugins/ecr
  when:
    branch:
    - develop
  settings:
    context: .
    dockerfile: docker/Dockerfile
    registry: 681372973860.dkr.ecr.eu-central-1.amazonaws.com
    repo: snp_admin
    tags:
    - "${DRONE_COMMIT_SHA:0:7}_ci_build_${DRONE_BUILD_NUMBER}"
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    region: eu-central-1
- name: "publish-release"
  image: plugins/ecr
  when:
    branch:
    - release/*
  settings:
    context: .
    dockerfile: docker/Dockerfile
    registry: 681372973860.dkr.ecr.eu-central-1.amazonaws.com
    repo: snp_admin
    tags:
    - "${DRONE_COMMIT_SHA:0:7}_ci_build_${DRONE_BUILD_NUMBER}"
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    region: eu-central-1
---
kind: pipeline
name: deploy-staging
type: kubernetes
depends_on:
- "build"
trigger:
  branch:
  - develop
  - drone
  event:
  - promote
  target:
  - staging
clone:
  disabled: true
steps:
- name: helm-update
  image: 310830963532.dkr.ecr.eu-central-1.amazonaws.com/drone-pipeline-img:25a4090
  environment:
    SSH_KEY:
      from_secret: ssh_key
    ARGOCD_USERNAME:
      from_secret: argocd-username
    ARGOCD_PASSWORD:
      from_secret: argocd-password
    ENV: staging
    PROJECT: snp
  commands:
  - ./.drone.sh
---
kind: pipeline
name: deploy-qa
type: kubernetes
depends_on:
- "build"
trigger:
  branch:
  - release/*
  event:
  - promote
  target:
  - qa
clone:
  disabled: true
steps:
- name: helm-update
  image: 310830963532.dkr.ecr.eu-central-1.amazonaws.com/drone-pipeline-img:25a4090
  environment:
    SSH_KEY:
      from_secret: ssh_key
    ARGOCD_USERNAME:
      from_secret: argocd-username
    ARGOCD_PASSWORD:
      from_secret: argocd-password
    ENV: qa
    PROJECT: snp
  commands:
  - ./.drone.sh
